### ISSUE TITLE
NOV (Neckar-Odenwald-Verkehrsverbund) is part of VRN

### ISSUE THREAD

**Issue by ManfredSchenk** [UlmApi/verbundkarte#1]
I think the NOV is part of the VRN, so the map is not 100% accurate in this area. Perhaps there are also other regions where some "Verbund" is part of another one.

**Comment by stkdiretto** [comment]
Yeah, I think I adapted the systematics [from this map](https://de.wikipedia.org/wiki/Datei:Karte_der_Verkehrsverb%C3%BCnde_und_Tarifverb%C3%BCnde_in_Deutschland.png) inconsistently – i.e., either both NOV and VGMT should be incorporated into VRN, or RMV needs to be split up into the daughter entities as well. I think I'll go for the former ;)

**Comment by stkdiretto** [comment]
fixed in #f958e0a
